package org.example;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
      driver = new ChromeDriver();
      js = (JavascriptExecutor) driver;
      vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
      driver.quit();
    }
    @Test
    public void registrationTest() {
      driver.get("https://transfer.wargaming.net/");
      driver.findElement(By.xpath("//div[3]/a")).click();
      vars.put("statusOK", js.executeScript("return document.evaluate(\"//body/div/div/div/div[2]/div/div/a\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue"));
      if ((Boolean) js.executeScript("return (arguments[0] !== null)", vars.get("statusOK"))) {
        driver.findElement(By.xpath("//body/div/div/div/div[2]/div/div/a")).click();
      }
      vars.put("randomEmail", js.executeScript("return Math.floor(Math.random()*1000000) + \"@example.com\""));
      driver.findElement(By.xpath("//input")).sendKeys(vars.get("randomEmail").toString());
      vars.put("randomUser", js.executeScript("return \"user7\" + Math.floor(Math.random()*10000000000)"));
      driver.findElement(By.xpath("//fieldset[2]/div/input")).sendKeys(vars.get("randomUser").toString());
      driver.findElement(By.xpath("//fieldset[3]/div/input")).sendKeys("AcceptablePassword123123");
      driver.findElement(By.xpath("//fieldset[4]/div/input")).sendKeys("AcceptablePassword123123");
      driver.findElement(By.xpath("//li/label")).click();
      driver.findElement(By.xpath("//button")).click();
    }
}
